site_name: Nebulo
site_description: Instant GraphQL API from PostgreSQL Database

theme:
    name: 'readthedocs'

repo_name: olirice/nebulo
repo_url: https://github.com/olirice/nebulo

nav:
    - Welcome:
        - Introduction: 'index.md'
        - Quickstart: 'quickstart.md'
    - Feature Support:
        - Types: 'supported_types.md'
        - Entities: 'supported_entities.md'
    - Examples:
        - SQLAlchemy Interop: 'sqlalchemy_interop.md'
    - Advanced:
        - Authentication: 'authentication.md'
        - Performance: 'performance.md'

markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.inlinehilite
