name: pre-commit hooks

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6

    - name: Install Pre-Commit
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit


    - name: Run Hooks
      run: |
        pre-commit run --all-files
